name: scheduled trigger

on:
 schedule:
  - cron: "*/5 * * * *"

jobs:
  test_external_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "schedule worflow"
        run: echo " => schedule workflow ..."

