name: Services

on:
  workflow_dispatch


jobs:
  init_depencies:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest

    steps:
    - name: "install redis-cli"
      run: sudo apt-get install -y redis
    - name: "check ping"
      run: redis-cli ping
