name: 02 basics events

on:
  # pull_request:
  #   types:
  #     closed

  push:
    branches:
      - main
      
jobs:
  print-hello-word:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print Hello World 2
        run : echo "Hello world 2"
