name: conditions
run-name: context running by ${{github.actor}} \#${{github.run_number}}

on:
  pull_request:
    types:
      - closed

jobs:
  test_external_trigger:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true}}
    steps:
      - name: "Print Hello World "
        run: echo "Hell world"

