name: create_container

on:
  workflow_dispatch:

jobs:
  setup_container:
    runs-on: ubuntu-latest
    steps:
      container:
        # image: dhi.io/node:25-debian13-sfw-ent-dev
        image: php:7.2

      - name: "check node version"
        run: php -v

