name: basic context

on: [workflow_dispatch]

jobs:
  test_external_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "show context 'github'"
        #run: echo " => show context 'github' ${{github.actor}}"
        #run: echo " => show context 'github' ${{github.event_name}}"
        run: echo " => show context 'github' ${{job.status}}"

