name: create_container

on:
  workflow_dispatch:

jobs:
  setup_container:
    runs-on: ubuntu-latest
    steps:
      - name: "setup container"
        run: echo "try setup container !!"
      - name: "check node version"
        run: node -v

