name: basic context

on: [workflow_dispach]

jobs:
  test_external_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "show context working"
        run: echo " => show context working ..."

