name: example 01

on:
  pull_request:
      types:
        - closed

jobs:
  example01:
    env:
        GH_TOKEN: ${{secrets.TOKEN_GITHUB}}
        NUM_REQUEST: ${{github.event.pull_request.number}}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: PR merged
        if: github.event.pull_request.merged == true
        run: gh pr comment $NUM_REQUEST --body "Votre PR est mérgé Beau travail bonne continuation.."

      - name: PR NOT merged
        if: github.event.pull_request.merged == false
        run: gh pr comment $NUM_REQUEST --body "Votre PR ne sera pas mergé, veuillez modifier votre code et ouvrir une nouvelle PR"

          # NUM_REQUEST: 18
      - name: as succeful
        run: echo "succeful"
