name: example 01

on:
  pull_request:
      types:
        - closed

jobs:
  example01:
    runs-on: ubuntu-latest

    steps:

      - name: run github cli
        run: gh pr comemnt $NUM_REQUEST --body "Votre PR ne sera pas mergé, veuillez modifier votre code et ouvrir une nouvelle PR"
        env:
          GH_TOKEN: ${{secrets.TOKEN_GITHUB}}
          # NUM_REQUEST: ${{github.event.number}}
          NUM_REQUEST: 18

      - name: as succeful
        run: echo "succeful"

      # - name: job1
      #   run: echo ${{toJson(github)}}
      #   run: echo ${{toJson(github)}}
