name: expressions workflow
run-name: "${{github.actor}} #${{github.run_number}}"

env:
  RUN_NUMBER: ${{ env.run_number > 1 && 'run 1er fois' ||'run plus qu une fois'}}

on:
  workflow_dispatch:


jobs:
  learn_expression:
    runs-on: ubuntu-latest
    steps:
      - name: "get status run number"
        run: echo ${{env.RUN_NUMBER}}
