name: Strategy Matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [20, 22]
        build: [development, production]

    steps:
      - name: "see Hello"
        run: echo "Hello on OS:(${{matrix.os}}) and (${{matrix.build}}) with (${{matrix.node}}) "
